languageCode = "es"
languageName = "Spanish"
weight = 1
title = "HUMANIZART"

[params]
displayName = "ES"
isoCode = "es"
rtl = false
dateFormat = "2 January 2006"
description = "Humanize your company again"
secondaryLogo = "android-chrome-512x512.png"
logo = "android-chrome-512x512.png"

[author]
name = "HUMANIZART"
headline = "Próximamente"
