[build]
  command = "hugo --gc --minify -D -b $URL"
  publish = "public"

[build.environment]
HUGO_THEMESDIR = "themes"
HUGO_THEME = "repo"
TZ = "Spain/Madrid"

[context.production.environment]
HUGO_VERSION = "0.121.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.2"

[context.branch-deploy]
command = "hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.121.2"
